name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                php: [ 7.4, 8.0, 8.1, 8.2, 8.3 ]
        name: PHP=${{ matrix.php }}
        runs-on: ubuntu-latest
        env:
            COMPOSER_NO_INTERACTION: 1
            XDEBUG_MODE: coverage
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: xdebug

            -   name: Install dependencies
                run: |
                    composer update --prefer-dist --no-interaction --no-progress

            -   name: Run tests
                run: composer test -- --coverage-clover ./coverage.xml

            -   name: Upload to Codecov
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: ./coverage.xml
                    verbose: true
